components:
  schemas:
    Error:
      properties:
        code:
          format: int64
          type: integer
        description:
          description: A detail description about the error message.
          type: string
        message:
          description: Error message.
          type: string
      type: object
    Product:
      properties:
        description:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        price:
          type: string
      type: object
    ProductList:
      properties:
        limit:
          format: int64
          type: integer
        list:
          items:
            $ref: '#/components/schemas/Product'
          type: array
        offset:
          format: int64
          type: integer
        total:
          format: int64
          type: integer
      type: object
      xml:
        name: Category
info:
  description: This is a server online store
  title: OnlineStore
  version: 1.0.0
openapi: 3.0.1
paths:
  /products:
    get:
      description: Get Product List
      parameters:
      - in: query
        name: start
        required: false
        schema:
          type: string
      - in: query
        name: count
        required: false
        schema:
          type: string
      - in: query
        name: params
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
          description: |
            OK.
            List of Products is returned.
    post:
      description: Add a Product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Product object that needs to be added to the store
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: |
            Created.
            Successful response with the newly created object as entity in the body.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: |
            Bad Request.
            Invalid request or validation error.
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: |
            Unsupported Media Type.
            The entity of the request was in a not supported format.
  /products/{productId}:
    get:
      description: Get a Product
      parameters:
       in: path
        name: productId
        required: true
        schema:
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: |
            OK.
            Product is returned.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: |
            Not Found
            Invalid product Id.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: |
            Internal Server Error
            Error while getting product
servers:
- url: https://3.15.18.64:8243/OnlineStore/1.0.0
